edit the files

diff --git a/scripts/stop_server b/scripts/stop_server
--- a/scripts/stop_server
+++ b/scripts/stop_server
@@ -1,12 +1,12 @@
 #!/bin/bash
-set -e
+sudo docker ps -a | grep final-python
+EXITCODE=$?
 
-# Check if the container is running
-if docker ps -q -f name=my_app_container; then
-    echo "Stopping the container..."
-    docker stop my_app_container
-    docker rm my_app_container
-    echo "Container stopped and removed."
+if [ "$EXITCODE" -ne "0" ]; then
+    echo "Container final-python not found."
+    exit 1  # Non-zero exit code for error state
 else
-    echo "Container is not running."
+    sudo docker stop final-python
+    sudo docker rm final-python
+    echo "Container final-python stopped and removed successfully."
 fi
